/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Data.TemperatureData;
import Data.TemperatureHistory;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;

/**
 *
 * @author comqsjb
 */
public class TemperatureUI extends javax.swing.JFrame implements PropertyChangeListener {

    /**
     * Creates new form TemperatureUI
     */
    TemperatureData td = new TemperatureData();
    TemperatureHistory th = new TemperatureHistory();
    
    
    public TemperatureUI() {
        initComponents();
        td.addPropertyChangeListener(this);
        th.addPropertyChangeListner(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupTempUnit = new javax.swing.ButtonGroup();
        txtTemperature = new javax.swing.JTextField();
        lblTemperature = new javax.swing.JLabel();
        btnCheck = new javax.swing.JButton();
        txtFeedback = new javax.swing.JTextField();
        rBtnCelsius = new javax.swing.JRadioButton();
        rBtnFahrenheit = new javax.swing.JRadioButton();
        taHistoryScrollPane = new javax.swing.JScrollPane();
        taHistory = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTemperature.setText("Please Input Your Temperature");

        btnCheck.setText("Check");
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });

        btnGroupTempUnit.add(rBtnCelsius);
        rBtnCelsius.setSelected(true);
        rBtnCelsius.setText("Celsius");
        rBtnCelsius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnCelsiusActionPerformed(evt);
            }
        });

        btnGroupTempUnit.add(rBtnFahrenheit);
        rBtnFahrenheit.setText("Fahrenheit");
        rBtnFahrenheit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnFahrenheitActionPerformed(evt);
            }
        });

        taHistory.setColumns(20);
        taHistory.setRows(5);
        taHistoryScrollPane.setViewportView(taHistory);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFeedback, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTemperature, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                            .addComponent(txtTemperature))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rBtnCelsius)
                            .addComponent(rBtnFahrenheit))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(taHistoryScrollPane))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(rBtnCelsius)
                .addGap(18, 18, 18)
                .addComponent(rBtnFahrenheit)
                .addGap(30, 30, 30)
                .addComponent(lblTemperature)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCheck))
                .addGap(18, 18, 18)
                .addComponent(txtFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(taHistoryScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
        // TODO add your handling code here:

        td.setTemperature(txtTemperature.getText());
        th.addReading(td);
//        td.setTemperature(txtTemperature.getText(), rBtnCelsius.isSelected());
        
    }//GEN-LAST:event_btnCheckActionPerformed

    private void rBtnCelsiusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnCelsiusActionPerformed
        // TODO add your handling code here:
        td.setCelciusScale();
        
    }//GEN-LAST:event_rBtnCelsiusActionPerformed

    private void rBtnFahrenheitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnFahrenheitActionPerformed
        // TODO add your handling code here:
        td.setFahrenheitScale();
        
    }//GEN-LAST:event_rBtnFahrenheitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TemperatureUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TemperatureUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TemperatureUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TemperatureUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TemperatureUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheck;
    private javax.swing.ButtonGroup btnGroupTempUnit;
    private javax.swing.JLabel lblTemperature;
    private javax.swing.JRadioButton rBtnCelsius;
    private javax.swing.JRadioButton rBtnFahrenheit;
    private javax.swing.JTextArea taHistory;
    private javax.swing.JScrollPane taHistoryScrollPane;
    private javax.swing.JTextField txtFeedback;
    private javax.swing.JTextField txtTemperature;
    // End of variables declaration//GEN-END:variables

    @Override
    public void propertyChange(PropertyChangeEvent evt) {
        if (evt.getPropertyName().equals("feedback")) 
            txtFeedback.setText(String.valueOf(evt.getNewValue()));
        
        if (evt.getPropertyName().equals("history")){
            this.taHistory.setText(String.valueOf(evt.getNewValue()));
        }
    }
}
